
package com.gauravkp.ws.soap.ts.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimeServiceImplService", targetNamespace = "http://ts.soap.ws.gauravkp.com/", wsdlLocation = "http://localhost:9876/ts?wsdl")
public class TimeServiceImplService
    extends Service
{

    private final static URL TIMESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TIMESERVICEIMPLSERVICE_QNAME = new QName("http://ts.soap.ws.gauravkp.com/", "TimeServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/ts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TIMESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TimeServiceImplService() {
        super(__getWsdlLocation(), TIMESERVICEIMPLSERVICE_QNAME);
    }

    public TimeServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMESERVICEIMPLSERVICE_QNAME, features);
    }

    public TimeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TIMESERVICEIMPLSERVICE_QNAME);
    }

    public TimeServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMESERVICEIMPLSERVICE_QNAME, features);
    }

    public TimeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServiceImplPort")
    public TimeService getTimeServiceImplPort() {
        return super.getPort(new QName("http://ts.soap.ws.gauravkp.com/", "TimeServiceImplPort"), TimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServiceImplPort")
    public TimeService getTimeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ts.soap.ws.gauravkp.com/", "TimeServiceImplPort"), TimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TIMESERVICEIMPLSERVICE_EXCEPTION;
        }
        return TIMESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
