package com.gauravkp.ws.soap.ts;

import java.net.MalformedURLException;

import com.gauravkp.ws.soap.ts.client.TimeService;
import com.gauravkp.ws.soap.ts.client.TimeServiceImplService;

/**
 * The actual client implementations {@link TimeService} and {@link TimeServiceImplService}
 * are generated by JDK utility wsimport 
 * 
 * wsimport -keep -p com.gauravkp.ws.soap.ts.client http://localhost:9876/ts?wsdl
 * 
 * by pointing to wsdl of service
 * @author Gaurav Panday
 *
 */
public class TimeServiceClient {

	public static void main(String[] args) throws MalformedURLException {
		TimeServiceImplService timeServiceImplService = new TimeServiceImplService();
		String serverTime = timeServiceImplService.getTimeServiceImplPort().getTimeAsString();
		System.out.println(serverTime);
	}

}
